### ISSUE TITLE
In the output of mag_gal, the third column (which indicates the values of extinction) are NOT set to zero, when NO extinction-law is set (2nd column==0). 

### ISSUE THREAD

**Issue by Mara2016** [lephare-photoz/lephare#261]
**Bug report**
in mag_gal, when we set the extinction law and the extinction values, also the case "no extinction law" is computed by default. In the ascii output this is visible by looking at the second column, which will have values 0, in addition to the number of extinction laws considered.  In the Lephare version, in the output of mag_gal, when the second column is set to zero ( no extinction law), the third column ( extinction value)  is set to zero by default. In Lephare++, the extinction values are applied also to the case "no extinction" and the colors of the template evolve. This should not happen.

**Comment by olivierilbert** [comment]
hello Mara,
there was a problem of header in the ascii file for QSO. I corrected it in the branch Improve-headers-displays.

But I don't think it was your problem, which is still unclear to me. If you allow a --EB_V 0, the attenuation curve doesn't mean anything since you don't apply attenuation. I think we put 0 by default to the law number. I tried to put  --EB_V 0.2,0.4, and I don't see any E(B-V)=0 in the ascii file. Maybe the problem was the wrong header? Could you try to show me an example of the problem, including the values of the relevant keywords.

**Comment by raphaelshirley** [comment]
In my example run I have four extinction models and as far as I understand the config these should only be applied to models 18 and up:

    'MOD_EXTINC':'18,26,26,33,26,33,26,33',
    'EXTINC_LAW':'SMC_prevot.dat,SB_calzetti.dat,SB_calzetti_bump1.dat,SB_calzetti_bump2.dat',  

In the output from mag_gal there are four values in column two 0,1,2,3 which seems to imply zero indexed extinction law ids. It is true that models with extinction law zero include models 1-17 and that they have different EBV values and different colours.

My understanding of what should happen is that 0 represents no extinction and they should only have one EBV value.

**Comment by Mara2016** [comment]
Hi Olivier,

 try to use 1 extinction law and a couple of extinction values.
What will happens is that for extinction law “0”, the column of the extinction values will_NOT have zeros, but actual values AND the magnitudes of the sources will also change.

Can you try ?
Thanks
Mara

**Comment by raphaelshirley** [comment]
For the QSO where I use only one extinction law col2 only takes the value 0 as if it is zero indexed for that one law and it does not apply zero extinction. Presumably that would not be a problem as an extinction law with zero EBV would be the same? However if the MOD_EXTINC value implies some models have no extinction applied that show that there is still an issue with that.

**Comment by olivierilbert** [comment]
if I understand well, that just a problem of convention. I think that in the c++ code, the first attenuation law has an ID set at 0.  So, 0 doesn't mean no attenuation. No attenuation corresponds to E(B-V)=0. And in such case EBV=0, the ID of the attenuation curve has no importance. Does it explain your results ?

I tried the case of Raphael, and I have only E(B-V)=0 for model between 1-17 which is normal. But you could have several values of E(B-V) with attenuation law=0 since it means the first curve. Same in the case of Mara.

Does it explain what you see ?

If yes, we could change the convention in the display and start at 1. And in fact, we have the same problem at few other places like the index of the filter in the header (starting at 0 while we use a start at 1 in the para file, which is inconsistent).

**Comment by raphaelshirley** [comment]
That seems consistent to me. I think it is just the zero index convention that has changed.

**Comment by Mara2016** [comment]
aahhhhh!

Does it mean that you do not create the templates for no_extinction by default anymore?

Yes, starting with the numbering from 1 would make more sense 
:)

Thanks
Mara

**Comment by olivierilbert** [comment]
Ok. So, I think it is our explanation. I wanted to check this problem of numbering starting at 0 in c++ that we don't change in the header. Let me close this issue and work in my current branch linked to display. thanks.

**Comment by Mara2016** [comment]
Hi Oliveir,
 you did not answer to my question.
In Fortran, if I was asking for an extinction law, the computation was done also for no_extinction.

Is it not the case anymore? Or do I remember wrongly ?

Thanks
Mara
